import 'package:flutter/material.dart';

class PrivacyPolicyPage extends StatelessWidget {
  const PrivacyPolicyPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Privacy Policy'),
      ),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: ListView(
          children: [
            Text(
              'Privacy Policy',
              style: TextStyle(fontSize: 24, fontWeight: FontWeight.bold),
            ),
            SizedBox(height: 8),
            Text('Last updated: November 08, 2024'),
            SizedBox(height: 16),
            Text(
              'This Privacy Policy describes Our policies and procedures on the collection, use, '
                  'and disclosure of Your information when You use the Service and tells You about '
                  'Your privacy rights and how the law protects You.',
              style: TextStyle(fontSize: 16),
            ),
            SizedBox(height: 16),
            _buildSectionTitle('Interpretation and Definitions'),
            _buildSectionTitle('Interpretation'),
            Text(
              'The words of which the initial letter is capitalized have meanings defined under the following conditions. '
                  'The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.',
            ),
            SizedBox(height: 8),
            _buildSectionTitle('Definitions'),
            Text(
              'For the purposes of this Privacy Policy:\n\n'
                  '- **Account**: A unique account created for You to access our Service or parts of our Service.\n'
                  '- **Affiliate**: An entity that controls, is controlled by or is under common control with a party, where “control” means ownership of 50% or more of the shares.\n'
                  '- **Application**: Mera Munshi, the software program provided by the Company.\n'
                  '- **Company**: Refers to Mera Munshi.\n'
                  '- **Country**: Pakistan\n'
                  '- **Device**: Any device that can access the Service such as a computer, a cellphone or a digital tablet.\n'
                  '- **Personal Data**: Any information that relates to an identified or identifiable individual.\n'
                  '- **Service**: Refers to the Application.\n'
                  '- **Service Provider**: Third-party companies or individuals employed by the Company to facilitate the Service.\n'
                  '- **Third-party Social Media Service**: Any social network website through which a User can log in or create an account to use the Service.\n'
                  '- **Usage Data**: Data collected automatically, generated by the use of the Service or from the Service infrastructure.\n'
                  '- **You**: The individual accessing or using the Service.',
            ),
            // Add additional sections for each part of the Privacy Policy
            _buildSectionTitle('Collecting and Using Your Personal Data'),
            _buildSectionTitle('Types of Data Collected'),
            _buildSectionTitle('Personal Data'),
            Text(
              'While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You...',
            ),
            SizedBox(height: 16),
            _buildSectionTitle('Usage Data'),
            Text(
              'Usage Data is collected automatically when using the Service...',
            ),
            // Add more sections similarly...
            _buildSectionTitle('Contact Us'),
            Text(
              'If you have any questions about this Privacy Policy, You can contact us:\n\n'
                  '- **By email**: mera_munshi@codeies.com',
              style: TextStyle(fontSize: 16),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildSectionTitle(String title) {
    return Padding(
      padding: const EdgeInsets.only(top: 16.0, bottom: 8.0),
      child: Text(
        title,
        style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
      ),
    );
  }
}
